# Generated by Django 4.2.7 on 2023-11-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0002_touristspot_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='comments',
            field=models.ManyToManyField(to='comments.comment'),
        ),
    ]
