# Generated by Django 4.2.7 on 2023-11-19 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizations', '0002_localization_latitude_localization_longitude_and_more'),
        ('core', '0004_touristspot_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='localization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localizations.localization'),
            preserve_default=False,
        ),
    ]
