# Generated by Django 4.2.7 on 2023-11-20 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizations', '0002_localization_latitude_localization_longitude_and_more'),
        ('core', '0005_touristspot_localization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='localization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizations.localization'),
        ),
    ]
