# Generated by Django 4.2.7 on 2023-11-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line', models.CharField(max_length=150)),
                ('second_line', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('estate', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=70)),
            ],
        ),
    ]
