# Generated by Django 4.2.7 on 2023-11-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localization',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localization',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localization',
            name='second_line',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
